<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.7.11-SNAPSHOT">
]
>

<object class="weka.experiment.Experiment" name="__root__" version="3.7.11-SNAPSHOT">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <object class="weka.classifiers.meta.ClassifierPerCluster" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">weka.clusterers.SimpleKMeans</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.functions.Logistic</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-C</object>
            <object class="java.lang.String" name="8">-R</object>
            <object class="java.lang.String" name="9">1.0E-8</object>
            <object class="java.lang.String" name="10">-M</object>
            <object class="java.lang.String" name="11">-1</object>
            <object class="java.lang.String" name="12">--</object>
            <object class="java.lang.String" name="13">-init</object>
            <object class="java.lang.String" name="14">0</object>
            <object class="java.lang.String" name="15">-max-candidates</object>
            <object class="java.lang.String" name="16">100</object>
            <object class="java.lang.String" name="17">-periodic-pruning</object>
            <object class="java.lang.String" name="18">10000</object>
            <object class="java.lang.String" name="19">-min-density</object>
            <object class="java.lang.String" name="20">2.0</object>
            <object class="java.lang.String" name="21">-t1</object>
            <object class="java.lang.String" name="22">-1.25</object>
            <object class="java.lang.String" name="23">-t2</object>
            <object class="java.lang.String" name="24">-1.0</object>
            <object class="java.lang.String" name="25">-N</object>
            <object class="java.lang.String" name="26">2</object>
            <object class="java.lang.String" name="27">-A</object>
            <object class="java.lang.String" name="28">weka.core.EuclideanDistance -R first-last</object>
            <object class="java.lang.String" name="29">-I</object>
            <object class="java.lang.String" name="30">500</object>
            <object class="java.lang.String" name="31">-num-slots</object>
            <object class="java.lang.String" name="32">1</object>
            <object class="java.lang.String" name="33">-S</object>
            <object class="java.lang.String" name="34">10</object>
         </object>
      </object>
   </object>
   <object class="javax.swing.DefaultListModel" name="datasets">
      <object class="java.io.File" name="0">/Users/admin/weka-3-7-10/data/cpu.arff</object>
   </object>
   <object class="int" name="runUpper" primitive="yes">10</object>
   <object class="weka.experiment.CrossValidationResultProducer" name="resultProducer">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-X</object>
         <object class="java.lang.String" name="1">10</object>
         <object class="java.lang.String" name="2">-O</object>
         <object class="java.lang.String" name="3">splitEvalutorOut.zip</object>
         <object class="java.lang.String" name="4">-W</object>
         <object class="java.lang.String" name="5">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="6">--</object>
         <object class="java.lang.String" name="7">-W</object>
         <object class="java.lang.String" name="8">weka.classifiers.rules.ZeroR</object>
         <object class="java.lang.String" name="9">-I</object>
         <object class="java.lang.String" name="10">0</object>
         <object class="java.lang.String" name="11">-C</object>
         <object class="java.lang.String" name="12">1</object>
         <object class="java.lang.String" name="13">--</object>
      </object>
   </object>
   <object class="boolean" name="usePropertyIterator" primitive="yes">true</object>
   <object array="yes" class="weka.experiment.PropertyNode" name="propertyPath">
      <object array="no" class="weka.experiment.PropertyNode" name="0" primitive="no">
         <object class="weka.experiment.ClassifierSplitEvaluator" name="value">
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-W</object>
               <object class="java.lang.String" name="1">weka.classifiers.rules.ZeroR</object>
               <object class="java.lang.String" name="2">-I</object>
               <object class="java.lang.String" name="3">0</object>
               <object class="java.lang.String" name="4">-C</object>
               <object class="java.lang.String" name="5">1</object>
               <object class="java.lang.String" name="6">--</object>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.CrossValidationResultProducer</object>
         <object class="java.lang.String" name="property">splitEvaluator</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="1" primitive="no">
         <object class="weka.classifiers.rules.ZeroR" name="value">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options"/>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="property">classifier</object>
      </object>
   </object>
   <object class="java.lang.String" name="notes"/>
   <object class="weka.experiment.InstancesResultListener" name="resultListener">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-O</object>
         <object class="java.lang.String" name="1">weka_experiment5257515661523203704.arff</object>
      </object>
      <object class="java.io.File" name="outputFile">/var/folders/jb/y0551jfj74sfhcjly12tp6sh0000gp/T/weka_experiment5257515661523203704.arff</object>
   </object>
   <object class="boolean" name="advanceDataSetFirst" primitive="yes">true</object>
   <object class="int" name="runLower" primitive="yes">1</object>
   <object class="java.lang.Boolean" name="classFirst">false</object>
</object>
